CREATE TABLE BOARD (
BOARD_SN INT(10) AUTO_INCREMENT PRIMARY KEY COMMENT '게시판순번',
SUBJECT VARCHAR(100) NOT NULL COMMENT '제목',
CONTENT LONGTEXT NOT NULL COMMENT '내용',
MEMBER_ID VARCHAR(100) NOT NULL COMMENT '회원아이디',
DELETE_YN VARCHAR(1) NOT NULL COMMENT '삭제여부',
REGIST_DATE DATETIME NOT NULL COMMENT '등록일자',
REGIST_IP VARCHAR(10) NOT NULL COMMENT '등록IP',
UPDATE_DATE DATETIME COMMENT '수정일자',
UPDATE_IP VARCHAR(10) COMMENT '수정IP'
) COMMENT '게시판';

CREATE TABLE MEMBERS (
MEMBER_ID VARCHAR(20) PRIMARY KEY COMMENT '회원아이디',
PASSWORD VARCHAR(50) NOT NULL COMMENT '암호',
AUTH_LEVEL VARCHAR(1) NOT NULL COMMENT '권한등급',
REGIST_DATE DATETIME NOT NULL COMMENT '등록일자',
REGIST_IP VARCHAR(10) NOT NULL COMMENT '등록IP',
UPDATE_DATE DATETIME COMMENT '수정일자',
UPDATE_IP VARCHAR(10) COMMENT '수정IP'
) COMMENT '회원';

CREATE TABLE ATTACH_FILE (
ATTACH_FILE_SN INT(10) AUTO_INCREMENT PRIMARY KEY COMMENT '첨부파일순번',
REAL_FILE_NAME VARCHAR(100) NOT NULL COMMENT '실제파일명',
STORED_FILE_NAME VARCHAR(100) NOT NULL COMMENT '저장파일명',
EXTENSION VARCHAR(10) NOT NULL COMMENT '확장자',
SIZED INT(10) NOT NULL COMMENT '크기',
SAVED_PATH VARCHAR(100) NOT NULL COMMENT '저장경로',
BOARD_SN INT(10) NOT NULL COMMENT '게시판순번',
REGIST_DATE DATETIME NOT NULL COMMENT '등록일자',
REGIST_IP VARCHAR(10) NOT NULL COMMENT '등록IP'
) COMMENT '첨부파일';

CREATE TABLE BOARD_COMMENT (
BOARD_COMMENT_SN INT(10) AUTO_INCREMENT PRIMARY KEY COMMENT '게시판댓글순번',
CONTENT LONGTEXT NOT NULL COMMENT '내용',
MEMBER_ID VARCHAR(100) NOT NULL COMMENT '회원아이디',
BOARD_SN INT(10) NOT NULL COMMENT '게시판순번',
DELETE_YN VARCHAR(1) NOT NULL COMMENT '삭제여부',
REGIST_DATE DATETIME NOT NULL COMMENT '등록일자',
REGIST_IP VARCHAR(10) NOT NULL COMMENT '등록IP',
UPDATE_DATE DATETIME COMMENT '수정일자',
UPDATE_IP VARCHAR(10) COMMENT '수정IP'
) COMMENT '게시판댓글';